load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "modular",
    srcs = [
        "base_dags.go",
        "dag_builder.go",
        "dynamic_runner.go",
        "graph.go",
        "helper.go",
        "operation.go",
        "operation_pool.go",
        "option.go",
        "planner.go",
        "resources.go",
        "state_tracker.go",
        "static_runner.go",
        "step.go",
        "step_builder.go",
        "test.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/cmd/roachtest/modular",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cmd/roachtest/cluster",
        "//pkg/cmd/roachtest/option",
        "//pkg/cmd/roachtest/roachtestutil/task",
        "//pkg/cmd/roachtest/test",
        "//pkg/roachprod/failureinjection/failures",
        "//pkg/roachprod/install",
        "//pkg/roachprod/logger",
        "//pkg/util/ctxgroup",
        "//pkg/util/randutil",
        "@com_github_cockroachdb_errors//:errors",
    ],
)

go_test(
    name = "modular_test",
    srcs = [
        "chain_merge_dynamic_test.go",
        "chain_merge_test.go",
        "dag_builder_test.go",
        "dynamic_name_e2e_test.go",
        "dynamic_name_integration_test.go",
        "dynamic_name_test.go",
        "json_test.go",
        "planner_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":modular"],
    deps = [
        "//pkg/roachprod/logger",
        "//pkg/testutils/echotest",
        "//pkg/util/randutil",
        "@com_github_stretchr_testify//require",
    ],
)
