// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cmd/roachtest/cluster/cluster_interface.go

<<<<<<<< HEAD:pkg/cmd/roachtest/cluster/mock/mock_cluster_generated.go
// Package mockcluster is a generated GoMock package.
package mockcluster
========
// Package cluster is a generated GoMock package.
package cluster
>>>>>>>> 439f3f02e1d (initial commit):pkg/cmd/roachtest/cluster/mock_cluster_generated.go

import (
	context "context"
	sql "database/sql"
	os "os"
	reflect "reflect"
	time "time"

	grafana "github.com/cockroachdb/cockroach/pkg/cmd/roachprod/grafana"
	option "github.com/cockroachdb/cockroach/pkg/cmd/roachtest/option"
	spec "github.com/cockroachdb/cockroach/pkg/cmd/roachtest/spec"
	roachprod "github.com/cockroachdb/cockroach/pkg/roachprod"
	failures "github.com/cockroachdb/cockroach/pkg/roachprod/failureinjection/failures"
	install "github.com/cockroachdb/cockroach/pkg/roachprod/install"
	logger "github.com/cockroachdb/cockroach/pkg/roachprod/logger"
	prometheus "github.com/cockroachdb/cockroach/pkg/roachprod/prometheus"
	vm "github.com/cockroachdb/cockroach/pkg/roachprod/vm"
	gomock "github.com/golang/mock/gomock"
)

// MockCluster is a mock of Cluster interface.
type MockCluster struct {
	ctrl     *gomock.Controller
	recorder *MockClusterMockRecorder
}

// MockClusterMockRecorder is the mock recorder for MockCluster.
type MockClusterMockRecorder struct {
	mock *MockCluster
}

// NewMockCluster creates a new mock instance.
func NewMockCluster(ctrl *gomock.Controller) *MockCluster {
	mock := &MockCluster{ctrl: ctrl}
	mock.recorder = &MockClusterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCluster) EXPECT() *MockClusterMockRecorder {
	return m.recorder
}

// AddGrafanaAnnotation mocks base method.
func (m *MockCluster) AddGrafanaAnnotation(ctx context.Context, l *logger.Logger, req grafana.AddAnnotationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGrafanaAnnotation", ctx, l, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGrafanaAnnotation indicates an expected call of AddGrafanaAnnotation.
func (mr *MockClusterMockRecorder) AddGrafanaAnnotation(ctx, l, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGrafanaAnnotation", reflect.TypeOf((*MockCluster)(nil).AddGrafanaAnnotation), ctx, l, req)
}

// AddInternalGrafanaAnnotation mocks base method.
func (m *MockCluster) AddInternalGrafanaAnnotation(ctx context.Context, l *logger.Logger, req grafana.AddAnnotationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInternalGrafanaAnnotation", ctx, l, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddInternalGrafanaAnnotation indicates an expected call of AddInternalGrafanaAnnotation.
func (mr *MockClusterMockRecorder) AddInternalGrafanaAnnotation(ctx, l, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInternalGrafanaAnnotation", reflect.TypeOf((*MockCluster)(nil).AddInternalGrafanaAnnotation), ctx, l, req)
}

// AdminUIPorts mocks base method.
func (m *MockCluster) AdminUIPorts(ctx context.Context, l *logger.Logger, node option.NodeListOption, tenant string, sqlInstance int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUIPorts", ctx, l, node, tenant, sqlInstance)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUIPorts indicates an expected call of AdminUIPorts.
func (mr *MockClusterMockRecorder) AdminUIPorts(ctx, l, node, tenant, sqlInstance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUIPorts", reflect.TypeOf((*MockCluster)(nil).AdminUIPorts), ctx, l, node, tenant, sqlInstance)
}

// All mocks base method.
func (m *MockCluster) All() option.NodeListOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].(option.NodeListOption)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockClusterMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockCluster)(nil).All))
}

// ApplySnapshots mocks base method.
func (m *MockCluster) ApplySnapshots(ctx context.Context, snapshots []vm.VolumeSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySnapshots", ctx, snapshots)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySnapshots indicates an expected call of ApplySnapshots.
func (mr *MockClusterMockRecorder) ApplySnapshots(ctx, snapshots interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySnapshots", reflect.TypeOf((*MockCluster)(nil).ApplySnapshots), ctx, snapshots)
}

// Architecture mocks base method.
func (m *MockCluster) Architecture() vm.CPUArch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Architecture")
	ret0, _ := ret[0].(vm.CPUArch)
	return ret0
}

// Architecture indicates an expected call of Architecture.
func (mr *MockClusterMockRecorder) Architecture() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Architecture", reflect.TypeOf((*MockCluster)(nil).Architecture))
}

// CRDBNodes mocks base method.
func (m *MockCluster) CRDBNodes() option.NodeListOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CRDBNodes")
	ret0, _ := ret[0].(option.NodeListOption)
	return ret0
}

// CRDBNodes indicates an expected call of CRDBNodes.
func (mr *MockClusterMockRecorder) CRDBNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CRDBNodes", reflect.TypeOf((*MockCluster)(nil).CRDBNodes))
}

// Cloud mocks base method.
func (m *MockCluster) Cloud() spec.Cloud {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud")
	ret0, _ := ret[0].(spec.Cloud)
	return ret0
}

// Cloud indicates an expected call of Cloud.
func (mr *MockClusterMockRecorder) Cloud() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockCluster)(nil).Cloud))
}

// Conn mocks base method.
func (m *MockCluster) Conn(ctx context.Context, l *logger.Logger, node int, opts ...option.OptionFunc) *sql.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, node}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Conn", varargs...)
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// Conn indicates an expected call of Conn.
func (mr *MockClusterMockRecorder) Conn(ctx, l, node interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, node}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Conn", reflect.TypeOf((*MockCluster)(nil).Conn), varargs...)
}

// ConnE mocks base method.
func (m *MockCluster) ConnE(ctx context.Context, l *logger.Logger, node int, opts ...option.OptionFunc) (*sql.DB, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, node}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConnE", varargs...)
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnE indicates an expected call of ConnE.
func (mr *MockClusterMockRecorder) ConnE(ctx, l, node interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, node}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnE", reflect.TypeOf((*MockCluster)(nil).ConnE), varargs...)
}

// CreateSnapshot mocks base method.
func (m *MockCluster) CreateSnapshot(ctx context.Context, snapshotPrefix string) ([]vm.VolumeSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, snapshotPrefix)
	ret0, _ := ret[0].([]vm.VolumeSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockClusterMockRecorder) CreateSnapshot(ctx, snapshotPrefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockCluster)(nil).CreateSnapshot), ctx, snapshotPrefix)
}

// DeleteSnapshots mocks base method.
func (m *MockCluster) DeleteSnapshots(ctx context.Context, snapshots ...vm.VolumeSnapshot) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range snapshots {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSnapshots", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshots indicates an expected call of DeleteSnapshots.
func (mr *MockClusterMockRecorder) DeleteSnapshots(ctx interface{}, snapshots ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, snapshots...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshots", reflect.TypeOf((*MockCluster)(nil).DeleteSnapshots), varargs...)
}

// DestroyDNS mocks base method.
func (m *MockCluster) DestroyDNS(ctx context.Context, l *logger.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyDNS", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyDNS indicates an expected call of DestroyDNS.
func (mr *MockClusterMockRecorder) DestroyDNS(ctx, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyDNS", reflect.TypeOf((*MockCluster)(nil).DestroyDNS), ctx, l)
}

// ExternalAddr mocks base method.
func (m *MockCluster) ExternalAddr(ctx context.Context, l *logger.Logger, node option.NodeListOption) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalAddr", ctx, l, node)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalAddr indicates an expected call of ExternalAddr.
func (mr *MockClusterMockRecorder) ExternalAddr(ctx, l, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalAddr", reflect.TypeOf((*MockCluster)(nil).ExternalAddr), ctx, l, node)
}

// ExternalAdminUIAddr mocks base method.
func (m *MockCluster) ExternalAdminUIAddr(ctx context.Context, l *logger.Logger, node option.NodeListOption, opts ...option.OptionFunc) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, node}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalAdminUIAddr", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalAdminUIAddr indicates an expected call of ExternalAdminUIAddr.
func (mr *MockClusterMockRecorder) ExternalAdminUIAddr(ctx, l, node interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, node}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalAdminUIAddr", reflect.TypeOf((*MockCluster)(nil).ExternalAdminUIAddr), varargs...)
}

// ExternalIP mocks base method.
func (m *MockCluster) ExternalIP(ctx context.Context, l *logger.Logger, node option.NodeListOption) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalIP", ctx, l, node)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalIP indicates an expected call of ExternalIP.
func (mr *MockClusterMockRecorder) ExternalIP(ctx, l, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalIP", reflect.TypeOf((*MockCluster)(nil).ExternalIP), ctx, l, node)
}

// ExternalPGUrl mocks base method.
func (m *MockCluster) ExternalPGUrl(ctx context.Context, l *logger.Logger, node option.NodeListOption, opts roachprod.PGURLOptions) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalPGUrl", ctx, l, node, opts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalPGUrl indicates an expected call of ExternalPGUrl.
func (mr *MockClusterMockRecorder) ExternalPGUrl(ctx, l, node, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalPGUrl", reflect.TypeOf((*MockCluster)(nil).ExternalPGUrl), ctx, l, node, opts)
}

// FetchDebugZip mocks base method.
func (m *MockCluster) FetchDebugZip(ctx context.Context, l *logger.Logger, dest string, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchDebugZip", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchDebugZip indicates an expected call of FetchDebugZip.
func (mr *MockClusterMockRecorder) FetchDebugZip(ctx, l, dest interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDebugZip", reflect.TypeOf((*MockCluster)(nil).FetchDebugZip), varargs...)
}

// FetchLogs mocks base method.
func (m *MockCluster) FetchLogs(ctx context.Context, l *logger.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLogs", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchLogs indicates an expected call of FetchLogs.
func (mr *MockClusterMockRecorder) FetchLogs(ctx, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLogs", reflect.TypeOf((*MockCluster)(nil).FetchLogs), ctx, l)
}

// FetchTimeseriesData mocks base method.
func (m *MockCluster) FetchTimeseriesData(ctx context.Context, l *logger.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTimeseriesData", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchTimeseriesData indicates an expected call of FetchTimeseriesData.
func (mr *MockClusterMockRecorder) FetchTimeseriesData(ctx, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTimeseriesData", reflect.TypeOf((*MockCluster)(nil).FetchTimeseriesData), ctx, l)
}

// Get mocks base method.
func (m *MockCluster) Get(ctx context.Context, l *logger.Logger, src, dest string, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, src, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockClusterMockRecorder) Get(ctx, l, src, dest interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, src, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCluster)(nil).Get), varargs...)
}

// GetFailer mocks base method.
func (m *MockCluster) GetFailer(l *logger.Logger, nodes option.NodeListOption, failureModeName string, disableStateValidation bool, opts ...failures.ClusterOptionFunc) (*failures.Failer, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{l, nodes, failureModeName, disableStateValidation}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFailer", varargs...)
	ret0, _ := ret[0].(*failures.Failer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailer indicates an expected call of GetFailer.
func (mr *MockClusterMockRecorder) GetFailer(l, nodes, failureModeName, disableStateValidation interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{l, nodes, failureModeName, disableStateValidation}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailer", reflect.TypeOf((*MockCluster)(nil).GetFailer), varargs...)
}

// GetPreemptedVMs mocks base method.
func (m *MockCluster) GetPreemptedVMs(ctx context.Context, l *logger.Logger) ([]vm.PreemptedVM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreemptedVMs", ctx, l)
	ret0, _ := ret[0].([]vm.PreemptedVM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreemptedVMs indicates an expected call of GetPreemptedVMs.
func (mr *MockClusterMockRecorder) GetPreemptedVMs(ctx, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreemptedVMs", reflect.TypeOf((*MockCluster)(nil).GetPreemptedVMs), ctx, l)
}

// GitClone mocks base method.
func (m *MockCluster) GitClone(ctx context.Context, l *logger.Logger, src, dest, branch string, node option.NodeListOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitClone", ctx, l, src, dest, branch, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// GitClone indicates an expected call of GitClone.
func (mr *MockClusterMockRecorder) GitClone(ctx, l, src, dest, branch, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitClone", reflect.TypeOf((*MockCluster)(nil).GitClone), ctx, l, src, dest, branch, node)
}

// Install mocks base method.
func (m *MockCluster) Install(ctx context.Context, l *logger.Logger, nodes option.NodeListOption, software ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, nodes}
	for _, a := range software {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Install", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockClusterMockRecorder) Install(ctx, l, nodes interface{}, software ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, nodes}, software...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockCluster)(nil).Install), varargs...)
}

// InternalAddr mocks base method.
func (m *MockCluster) InternalAddr(ctx context.Context, l *logger.Logger, node option.NodeListOption) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalAddr", ctx, l, node)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalAddr indicates an expected call of InternalAddr.
func (mr *MockClusterMockRecorder) InternalAddr(ctx, l, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalAddr", reflect.TypeOf((*MockCluster)(nil).InternalAddr), ctx, l, node)
}

// InternalAdminUIAddr mocks base method.
func (m *MockCluster) InternalAdminUIAddr(ctx context.Context, l *logger.Logger, node option.NodeListOption, opts ...option.OptionFunc) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, node}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InternalAdminUIAddr", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalAdminUIAddr indicates an expected call of InternalAdminUIAddr.
func (mr *MockClusterMockRecorder) InternalAdminUIAddr(ctx, l, node interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, node}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalAdminUIAddr", reflect.TypeOf((*MockCluster)(nil).InternalAdminUIAddr), varargs...)
}

// InternalIP mocks base method.
func (m *MockCluster) InternalIP(ctx context.Context, l *logger.Logger, node option.NodeListOption) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalIP", ctx, l, node)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalIP indicates an expected call of InternalIP.
func (mr *MockClusterMockRecorder) InternalIP(ctx, l, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalIP", reflect.TypeOf((*MockCluster)(nil).InternalIP), ctx, l, node)
}

// InternalPGUrl mocks base method.
func (m *MockCluster) InternalPGUrl(ctx context.Context, l *logger.Logger, node option.NodeListOption, opts roachprod.PGURLOptions) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalPGUrl", ctx, l, node, opts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalPGUrl indicates an expected call of InternalPGUrl.
func (mr *MockClusterMockRecorder) InternalPGUrl(ctx, l, node, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalPGUrl", reflect.TypeOf((*MockCluster)(nil).InternalPGUrl), ctx, l, node, opts)
}

// IsLocal mocks base method.
func (m *MockCluster) IsLocal() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocal")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLocal indicates an expected call of IsLocal.
func (mr *MockClusterMockRecorder) IsLocal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocal", reflect.TypeOf((*MockCluster)(nil).IsLocal))
}

// IsSecure mocks base method.
func (m *MockCluster) IsSecure() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSecure")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSecure indicates an expected call of IsSecure.
func (mr *MockClusterMockRecorder) IsSecure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSecure", reflect.TypeOf((*MockCluster)(nil).IsSecure))
}

// ListSnapshots mocks base method.
func (m *MockCluster) ListSnapshots(ctx context.Context, vslo vm.VolumeSnapshotListOpts) ([]vm.VolumeSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshots", ctx, vslo)
	ret0, _ := ret[0].([]vm.VolumeSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockClusterMockRecorder) ListSnapshots(ctx, vslo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockCluster)(nil).ListSnapshots), ctx, vslo)
}

// MakeNodes mocks base method.
func (m *MockCluster) MakeNodes(opts ...option.Option) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeNodes", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// MakeNodes indicates an expected call of MakeNodes.
func (mr *MockClusterMockRecorder) MakeNodes(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeNodes", reflect.TypeOf((*MockCluster)(nil).MakeNodes), opts...)
}

// Name mocks base method.
func (m *MockCluster) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockClusterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCluster)(nil).Name))
}

// NewDeprecatedMonitor mocks base method.
func (m *MockCluster) NewDeprecatedMonitor(arg0 context.Context, arg1 ...option.Option) Monitor {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewDeprecatedMonitor", varargs...)
	ret0, _ := ret[0].(Monitor)
	return ret0
}

// NewDeprecatedMonitor indicates an expected call of NewDeprecatedMonitor.
func (mr *MockClusterMockRecorder) NewDeprecatedMonitor(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDeprecatedMonitor", reflect.TypeOf((*MockCluster)(nil).NewDeprecatedMonitor), varargs...)
}

// Node mocks base method.
func (m *MockCluster) Node(i int) option.NodeListOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node", i)
	ret0, _ := ret[0].(option.NodeListOption)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockClusterMockRecorder) Node(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockCluster)(nil).Node), i)
}

// Nodes mocks base method.
func (m *MockCluster) Nodes(ns ...int) option.NodeListOption {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range ns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Nodes", varargs...)
	ret0, _ := ret[0].(option.NodeListOption)
	return ret0
}

// Nodes indicates an expected call of Nodes.
func (mr *MockClusterMockRecorder) Nodes(ns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nodes", reflect.TypeOf((*MockCluster)(nil).Nodes), ns...)
}

// PopulateEtcHosts mocks base method.
func (m *MockCluster) PopulateEtcHosts(ctx context.Context, l *logger.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopulateEtcHosts", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// PopulateEtcHosts indicates an expected call of PopulateEtcHosts.
func (mr *MockClusterMockRecorder) PopulateEtcHosts(ctx, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopulateEtcHosts", reflect.TypeOf((*MockCluster)(nil).PopulateEtcHosts), ctx, l)
}

// Put mocks base method.
func (m *MockCluster) Put(ctx context.Context, src, dest string, opts ...option.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, src, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Put", varargs...)
}

// Put indicates an expected call of Put.
func (mr *MockClusterMockRecorder) Put(ctx, src, dest interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, src, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockCluster)(nil).Put), varargs...)
}

// PutE mocks base method.
func (m *MockCluster) PutE(ctx context.Context, l *logger.Logger, src, dest string, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, src, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutE", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutE indicates an expected call of PutE.
func (mr *MockClusterMockRecorder) PutE(ctx, l, src, dest interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, src, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutE", reflect.TypeOf((*MockCluster)(nil).PutE), varargs...)
}

// PutLibraries mocks base method.
func (m *MockCluster) PutLibraries(ctx context.Context, libraryDir string, libraries []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutLibraries", ctx, libraryDir, libraries)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutLibraries indicates an expected call of PutLibraries.
func (mr *MockClusterMockRecorder) PutLibraries(ctx, libraryDir, libraries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutLibraries", reflect.TypeOf((*MockCluster)(nil).PutLibraries), ctx, libraryDir, libraries)
}

// PutString mocks base method.
func (m *MockCluster) PutString(ctx context.Context, content, dest string, mode os.FileMode, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, content, dest, mode}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutString", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutString indicates an expected call of PutString.
func (mr *MockClusterMockRecorder) PutString(ctx, content, dest, mode interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, content, dest, mode}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutString", reflect.TypeOf((*MockCluster)(nil).PutString), varargs...)
}

// Range mocks base method.
func (m *MockCluster) Range(begin, end int) option.NodeListOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range", begin, end)
	ret0, _ := ret[0].(option.NodeListOption)
	return ret0
}

// Range indicates an expected call of Range.
func (mr *MockClusterMockRecorder) Range(begin, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockCluster)(nil).Range), begin, end)
}

// RefetchCertsFromNode mocks base method.
func (m *MockCluster) RefetchCertsFromNode(ctx context.Context, node int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefetchCertsFromNode", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefetchCertsFromNode indicates an expected call of RefetchCertsFromNode.
func (mr *MockClusterMockRecorder) RefetchCertsFromNode(ctx, node interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefetchCertsFromNode", reflect.TypeOf((*MockCluster)(nil).RefetchCertsFromNode), ctx, node)
}

// Reformat mocks base method.
func (m *MockCluster) Reformat(ctx context.Context, l *logger.Logger, node option.NodeListOption, filesystem string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reformat", ctx, l, node, filesystem)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reformat indicates an expected call of Reformat.
func (mr *MockClusterMockRecorder) Reformat(ctx, l, node, filesystem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reformat", reflect.TypeOf((*MockCluster)(nil).Reformat), ctx, l, node, filesystem)
}

// RegisterClusterHook mocks base method.
func (m *MockCluster) RegisterClusterHook(hookName string, hookType option.ClusterHookType, timeout time.Duration, hook func(context.Context) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterClusterHook", hookName, hookType, timeout, hook)
}

// RegisterClusterHook indicates an expected call of RegisterClusterHook.
func (mr *MockClusterMockRecorder) RegisterClusterHook(hookName, hookType, timeout, hook interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClusterHook", reflect.TypeOf((*MockCluster)(nil).RegisterClusterHook), hookName, hookType, timeout, hook)
}

// Reset mocks base method.
func (m *MockCluster) Reset(ctx context.Context, l *logger.Logger, nodes option.NodeListOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, l, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockClusterMockRecorder) Reset(ctx, l, nodes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockCluster)(nil).Reset), ctx, l, nodes)
}

// Run mocks base method.
func (m *MockCluster) Run(ctx context.Context, options install.RunOptions, args ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, options}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Run", varargs...)
}

// Run indicates an expected call of Run.
func (mr *MockClusterMockRecorder) Run(ctx, options interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, options}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCluster)(nil).Run), varargs...)
}

// RunE mocks base method.
func (m *MockCluster) RunE(ctx context.Context, options install.RunOptions, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, options}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunE", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunE indicates an expected call of RunE.
func (mr *MockClusterMockRecorder) RunE(ctx, options interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, options}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunE", reflect.TypeOf((*MockCluster)(nil).RunE), varargs...)
}

// RunWithDetails mocks base method.
func (m *MockCluster) RunWithDetails(ctx context.Context, testLogger *logger.Logger, options install.RunOptions, args ...string) ([]install.RunResultDetails, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, testLogger, options}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithDetails", varargs...)
	ret0, _ := ret[0].([]install.RunResultDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWithDetails indicates an expected call of RunWithDetails.
func (mr *MockClusterMockRecorder) RunWithDetails(ctx, testLogger, options interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, testLogger, options}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithDetails", reflect.TypeOf((*MockCluster)(nil).RunWithDetails), varargs...)
}

// RunWithDetailsSingleNode mocks base method.
func (m *MockCluster) RunWithDetailsSingleNode(ctx context.Context, testLogger *logger.Logger, options install.RunOptions, args ...string) (install.RunResultDetails, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, testLogger, options}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithDetailsSingleNode", varargs...)
	ret0, _ := ret[0].(install.RunResultDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWithDetailsSingleNode indicates an expected call of RunWithDetailsSingleNode.
func (mr *MockClusterMockRecorder) RunWithDetailsSingleNode(ctx, testLogger, options interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, testLogger, options}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithDetailsSingleNode", reflect.TypeOf((*MockCluster)(nil).RunWithDetailsSingleNode), varargs...)
}

// SQLPorts mocks base method.
func (m *MockCluster) SQLPorts(ctx context.Context, l *logger.Logger, node option.NodeListOption, tenant string, sqlInstance int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SQLPorts", ctx, l, node, tenant, sqlInstance)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SQLPorts indicates an expected call of SQLPorts.
func (mr *MockClusterMockRecorder) SQLPorts(ctx, l, node, tenant, sqlInstance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SQLPorts", reflect.TypeOf((*MockCluster)(nil).SQLPorts), ctx, l, node, tenant, sqlInstance)
}

// SetDefaultVirtualCluster mocks base method.
func (m *MockCluster) SetDefaultVirtualCluster(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefaultVirtualCluster", arg0)
}

// SetDefaultVirtualCluster indicates an expected call of SetDefaultVirtualCluster.
func (mr *MockClusterMockRecorder) SetDefaultVirtualCluster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultVirtualCluster", reflect.TypeOf((*MockCluster)(nil).SetDefaultVirtualCluster), arg0)
}

// SetRandomSeed mocks base method.
func (m *MockCluster) SetRandomSeed(seed int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRandomSeed", seed)
}

// SetRandomSeed indicates an expected call of SetRandomSeed.
func (mr *MockClusterMockRecorder) SetRandomSeed(seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRandomSeed", reflect.TypeOf((*MockCluster)(nil).SetRandomSeed), seed)
}

// Signal mocks base method.
func (m *MockCluster) Signal(ctx context.Context, l *logger.Logger, sig int, opts ...option.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, sig}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Signal", varargs...)
}

// Signal indicates an expected call of Signal.
func (mr *MockClusterMockRecorder) Signal(ctx, l, sig interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, sig}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockCluster)(nil).Signal), varargs...)
}

// SignalE mocks base method.
func (m *MockCluster) SignalE(ctx context.Context, l *logger.Logger, sig int, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, sig}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignalE", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalE indicates an expected call of SignalE.
func (mr *MockClusterMockRecorder) SignalE(ctx, l, sig interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, sig}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalE", reflect.TypeOf((*MockCluster)(nil).SignalE), varargs...)
}

// Spec mocks base method.
func (m *MockCluster) Spec() spec.ClusterSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spec")
	ret0, _ := ret[0].(spec.ClusterSpec)
	return ret0
}

// Spec indicates an expected call of Spec.
func (mr *MockClusterMockRecorder) Spec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spec", reflect.TypeOf((*MockCluster)(nil).Spec))
}

// Stage mocks base method.
func (m *MockCluster) Stage(ctx context.Context, l *logger.Logger, application, versionOrSHA, dir string, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, application, versionOrSHA, dir}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Stage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stage indicates an expected call of Stage.
func (mr *MockClusterMockRecorder) Stage(ctx, l, application, versionOrSHA, dir interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, application, versionOrSHA, dir}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stage", reflect.TypeOf((*MockCluster)(nil).Stage), varargs...)
}

// Start mocks base method.
func (m *MockCluster) Start(ctx context.Context, l *logger.Logger, startOpts option.StartOpts, settings install.ClusterSettings, opts ...option.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, startOpts, settings}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Start", varargs...)
}

// Start indicates an expected call of Start.
func (mr *MockClusterMockRecorder) Start(ctx, l, startOpts, settings interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, startOpts, settings}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCluster)(nil).Start), varargs...)
}

// StartE mocks base method.
func (m *MockCluster) StartE(ctx context.Context, l *logger.Logger, startOpts option.StartOpts, settings install.ClusterSettings, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, startOpts, settings}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartE", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartE indicates an expected call of StartE.
func (mr *MockClusterMockRecorder) StartE(ctx, l, startOpts, settings interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, startOpts, settings}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartE", reflect.TypeOf((*MockCluster)(nil).StartE), varargs...)
}

// StartGrafana mocks base method.
func (m *MockCluster) StartGrafana(ctx context.Context, l *logger.Logger, promCfg *prometheus.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGrafana", ctx, l, promCfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartGrafana indicates an expected call of StartGrafana.
func (mr *MockClusterMockRecorder) StartGrafana(ctx, l, promCfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGrafana", reflect.TypeOf((*MockCluster)(nil).StartGrafana), ctx, l, promCfg)
}

// StartServiceForVirtualCluster mocks base method.
func (m *MockCluster) StartServiceForVirtualCluster(ctx context.Context, l *logger.Logger, startOpts option.StartOpts, settings install.ClusterSettings) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartServiceForVirtualCluster", ctx, l, startOpts, settings)
}

// StartServiceForVirtualCluster indicates an expected call of StartServiceForVirtualCluster.
func (mr *MockClusterMockRecorder) StartServiceForVirtualCluster(ctx, l, startOpts, settings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServiceForVirtualCluster", reflect.TypeOf((*MockCluster)(nil).StartServiceForVirtualCluster), ctx, l, startOpts, settings)
}

// StartServiceForVirtualClusterE mocks base method.
func (m *MockCluster) StartServiceForVirtualClusterE(ctx context.Context, l *logger.Logger, startOpts option.StartOpts, settings install.ClusterSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartServiceForVirtualClusterE", ctx, l, startOpts, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartServiceForVirtualClusterE indicates an expected call of StartServiceForVirtualClusterE.
func (mr *MockClusterMockRecorder) StartServiceForVirtualClusterE(ctx, l, startOpts, settings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServiceForVirtualClusterE", reflect.TypeOf((*MockCluster)(nil).StartServiceForVirtualClusterE), ctx, l, startOpts, settings)
}

// Stop mocks base method.
func (m *MockCluster) Stop(ctx context.Context, l *logger.Logger, stopOpts option.StopOpts, opts ...option.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, stopOpts}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Stop", varargs...)
}

// Stop indicates an expected call of Stop.
func (mr *MockClusterMockRecorder) Stop(ctx, l, stopOpts interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, stopOpts}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCluster)(nil).Stop), varargs...)
}

// StopE mocks base method.
func (m *MockCluster) StopE(ctx context.Context, l *logger.Logger, stopOpts option.StopOpts, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l, stopOpts}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopE", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopE indicates an expected call of StopE.
func (mr *MockClusterMockRecorder) StopE(ctx, l, stopOpts interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l, stopOpts}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopE", reflect.TypeOf((*MockCluster)(nil).StopE), varargs...)
}

// StopGrafana mocks base method.
func (m *MockCluster) StopGrafana(ctx context.Context, l *logger.Logger, dumpDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopGrafana", ctx, l, dumpDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopGrafana indicates an expected call of StopGrafana.
func (mr *MockClusterMockRecorder) StopGrafana(ctx, l, dumpDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopGrafana", reflect.TypeOf((*MockCluster)(nil).StopGrafana), ctx, l, dumpDir)
}

// StopServiceForVirtualCluster mocks base method.
func (m *MockCluster) StopServiceForVirtualCluster(ctx context.Context, l *logger.Logger, stopOpts option.StopOpts) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopServiceForVirtualCluster", ctx, l, stopOpts)
}

// StopServiceForVirtualCluster indicates an expected call of StopServiceForVirtualCluster.
func (mr *MockClusterMockRecorder) StopServiceForVirtualCluster(ctx, l, stopOpts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopServiceForVirtualCluster", reflect.TypeOf((*MockCluster)(nil).StopServiceForVirtualCluster), ctx, l, stopOpts)
}

// StopServiceForVirtualClusterE mocks base method.
func (m *MockCluster) StopServiceForVirtualClusterE(ctx context.Context, l *logger.Logger, stopOpts option.StopOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopServiceForVirtualClusterE", ctx, l, stopOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopServiceForVirtualClusterE indicates an expected call of StopServiceForVirtualClusterE.
func (mr *MockClusterMockRecorder) StopServiceForVirtualClusterE(ctx, l, stopOpts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopServiceForVirtualClusterE", reflect.TypeOf((*MockCluster)(nil).StopServiceForVirtualClusterE), ctx, l, stopOpts)
}

// Wipe mocks base method.
func (m *MockCluster) Wipe(ctx context.Context, opts ...option.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Wipe", varargs...)
}

// Wipe indicates an expected call of Wipe.
func (mr *MockClusterMockRecorder) Wipe(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wipe", reflect.TypeOf((*MockCluster)(nil).Wipe), varargs...)
}

// WipeE mocks base method.
func (m *MockCluster) WipeE(ctx context.Context, l *logger.Logger, opts ...option.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, l}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WipeE", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WipeE indicates an expected call of WipeE.
func (mr *MockClusterMockRecorder) WipeE(ctx, l interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, l}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WipeE", reflect.TypeOf((*MockCluster)(nil).WipeE), varargs...)
}

// WorkloadNode mocks base method.
func (m *MockCluster) WorkloadNode() option.NodeListOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkloadNode")
	ret0, _ := ret[0].(option.NodeListOption)
	return ret0
}

// WorkloadNode indicates an expected call of WorkloadNode.
func (mr *MockClusterMockRecorder) WorkloadNode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkloadNode", reflect.TypeOf((*MockCluster)(nil).WorkloadNode))
}
