load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "operations",
    srcs = [
        "add_index.go",
        "backup_restore.go",
        "cluster_setting.go",
        "inspect.go",
        "node_restart.go",
        "replication.go",
        "schema_change.go",
        "tpcc.go",
        "ycsb.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/cmd/roachtest/modular/operations",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cmd/roachtest/cluster",
        "//pkg/cmd/roachtest/modular",
        "//pkg/cmd/roachtest/option",
        "//pkg/cmd/roachtest/roachtestutil",
        "//pkg/cmd/roachtest/test",
        "//pkg/jobs",
        "//pkg/roachprod",
        "//pkg/roachprod/logger",
        "//pkg/sql/catalog/catpb",
        "//pkg/sql/randgen",
        "//pkg/sql/sem/tree",
        "//pkg/sql/types",
        "//pkg/testutils",
        "//pkg/testutils/fingerprintutils",
        "//pkg/util/hlc",
        "//pkg/util/randutil",
        "//pkg/util/timeutil",
        "@com_github_lib_pq//oid",
    ],
)
