load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "directory-server_lib",
    srcs = ["main.go"],
    importpath = "github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachtestutil/directory-server",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/ccl/sqlproxyccl/tenant",
        "//pkg/ccl/sqlproxyccl/tenantdirsvr",
        "//pkg/roachpb",
        "//pkg/util/stop",
        "//pkg/util/timeutil",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "directory-server",
    embed = [":directory-server_lib"],
    visibility = ["//visibility:public"],
)
